/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCodeSnippet: typeof import('./src/components/base/BaseCodeSnippet.vue')['default']
    BaseCopyButton: typeof import('./src/components/base/BaseCopyButton.vue')['default']
    BaseFormTextField: typeof import('./src/components/base/BaseFormTextField.vue')['default']
    BaseLink: typeof import('./src/components/base/BaseLink.vue')['default']
    BaseLinkDocumentation: typeof import('./src/components/base/BaseLinkDocumentation.vue')['default']
    BaseMessageBox: typeof import('./src/components/base/BaseMessageBox.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseRefreshButton: typeof import('./src/components/base/BaseRefreshButton.vue')['default']
    BaseSwitch: typeof import('./src/components/base/BaseSwitch.vue')['default']
    BaseTextField: typeof import('src/components/base/BaseTextField.vue')['default']
    BaseUploadFile: typeof import('./src/components/base/BaseUploadFile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
