from canarytokens.constants import INVOCATION_ID_LENGTH
from canarytokens.models import Hostname

REG_TEMPLATE = r"""Windows Registry Editor Version 5.00
; Sensitive command token generated by Thinkst Canary
; Run the following commands with admin privs on a Windows machine:
;   reg import FILENAME /reg:64
;   reg import FILENAME /reg:32

; command that will be watched for
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\{PROCESS}]
"GlobalFlag"=dword:00000200

; magic unique canarytoken that will be fired when this command is executed
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\{PROCESS}]
"ReportingMode"=dword:00000001
"MonitorProcess"="cmd.exe /c start /min powershell.exe -windowstyle hidden -command \"$($u=$(\\\"u$env:username\\\" -replace('[^a-zA-Z0-9\\-]+', ''))[0..63] -join '';$c=$(\\\"c$env:computername\\\" -replace('[^a-zA-Z0-9\\-]+', ''))[0..63] -join ''; $id=\\\"\\\"; 1..{INVOCATION_ID_LENGTH} | foreach-object {{ $id += [Char[]]\\\"abcdefhijklmnonpqrstuvwxyz0123456789\\\" | Get-Random }}; Resolve-DnsName -Name \\\"$c.UN.$u.CMD.$id.{TOKEN_DNS}\\\")\""
"""


def make_canary_msreg(token_hostname: Hostname, process_name: str = "klist.exe") -> str:
    """Returns a Microsoft Register .reg file which has a canarytoken and
    process name embedded in it.
    The token is in a 'hostname' eg: {some}.{thing}.CMD.{token}.{canarytoken_hostname}

    Args:
        token_hostname (Hostname): {token}.{canarytoken_server_hostname} eg: 1234dsaa.canarytokens.com
        process_name (str, optional): Name of the process to monitor.
                                      If extension is not .exe .exe is appended. Defaults to 'klist.exe'.

    Returns:
        StringIO: a valid .reg file that is to be loaded on a windows machine.
    """
    # TODO: use .endswith.
    if process_name.find(".exe") == -1:
        process_name += ".exe"

    return REG_TEMPLATE.format(
        TOKEN_DNS=token_hostname,
        PROCESS=process_name,
        INVOCATION_ID_LENGTH=INVOCATION_ID_LENGTH,
    )
