
OUTPUT_CHANNEL_EMAIL = 'Email'
OUTPUT_CHANNEL_TWILIO_SMS   = 'TwilioSMS'

INPUT_CHANNEL_HTTP     = 'HTTP'
INPUT_CHANNEL_DNS      = 'DNS'
INPUT_CHANNEL_IMGUR    = 'Imgur'
INPUT_CHANNEL_LINKEDIN = 'LinkedIn'
INPUT_CHANNEL_BITCOIN  = 'Bitcoin'
INPUT_CHANNEL_SMTP     = 'SMTP'
